# Generated by Django 5.2.1 on 2025-06-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('auteur', 'Auteur'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20, verbose_name='rôle'),
        ),
    ]
