# Generated by Django 5.2.1 on 2025-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='contenu')),
                ('excerpt', models.TextField(blank=True, help_text="Résumé de l'article (max 300 caractères)", max_length=300, verbose_name='extrait')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='image de couverture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='nombre de likes')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='nombre de partages')),
                ('meta_title', models.CharField(blank=True, help_text='Titre pour le référencement (max 60 caractères)', max_length=60, verbose_name='titre SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Description pour le référencement (max 160 caractères)', max_length=160, verbose_name='description SEO')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('couleur', models.CharField(default='#007bff', help_text='Code couleur hexadécimal (ex: #007bff)', max_length=7, verbose_name='couleur')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: fas fa-tag)", max_length=50, verbose_name='icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('couleur', models.CharField(default='#6c757d', help_text='Code couleur hexadécimal (ex: #6c757d)', max_length=7, verbose_name='couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
    ]
