# Generated by Django 5.2.1 on 2025-06-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'catégorie', 'verbose_name_plural': 'catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='couleur',
            field=models.CharField(default='#007bff', help_text='Code couleur hexadécimal (ex: #007bff)', max_length=7, verbose_name='couleur'),
        ),
        migrations.AddField(
            model_name='category',
            name='icone',
            field=models.CharField(blank=True, help_text="Nom de l'icône (ex: fas fa-tag)", max_length=50, verbose_name='icône'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_category_slug'),
        ),
    ]
